# Generated by Django 4.0.4 on 2022-05-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='topic',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='noticia',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
