# Generated by Django 4.0.4 on 2022-05-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_topic_noticia_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.URLField(blank=True),
        ),
    ]
