# Generated by Django 4.0.4 on 2022-05-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_noticia_date_alter_noticia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='date',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
