# Generated by Django 4.0.4 on 2022-05-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='img',
            field=models.URLField(blank=True),
        ),
    ]
