# Generated by Django 4.0.4 on 2022-05-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='img',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
