# Generated by Django 4.0.4 on 2022-05-30 21:08

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercioalipage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='comercios.comerciocategory'),
        ),
        migrations.AddField(
            model_name='comercioalipage',
            name='coord',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='comercioalipage',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='comercioalipage',
            name='imagen',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='comercioalipage',
            name='nombre',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
