# Generated by Django 4.0.4 on 2022-05-30 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0002_comercioalipage_categories_comercioalipage_coord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comercioalipage',
            name='nombre',
        ),
    ]
