# Generated by Django 4.0.4 on 2022-05-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0003_remove_comercioalipage_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='link',
        ),
        migrations.AddField(
            model_name='producto',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
