# Generated by Django 4.0.4 on 2022-06-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('comercios', '0004_remove_producto_link_producto_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComercioAliPage',
            new_name='ComercioPage',
        ),

    ]
