# Generated by Django 4.0.4 on 2022-06-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('comercios', '0005_rename_comercioalipage_comerciopage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComercioPage',
            new_name='ComercioAliPage',
        ),
    ]
