# Generated by Django 4.0.4 on 2022-06-02 18:18

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0006_rename_comerciopage_comercioalipage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('url', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('image', models.URLField()),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='comercios.comerciocategory')),
            ],
        ),
    ]
