# Generated by Django 4.0.4 on 2022-06-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0007_comercio'),
    ]

    operations = [


        migrations.AddField(
            model_name='comercio',
            name='coord',
            field=models.CharField(blank=True, max_length=20),
        ),



    ]
