# Generated by Django 4.0.4 on 2022-06-02 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('comercios', '0008_remove_comerciomodpage_page_ptr_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComercioAliPage',
            new_name='ComercioPage',
        ),



    ]
